[global]
developmentMode = false

[server]
headless = true
runOnSave = false
port = 8501
address = "localhost"

[client]
showErrorDetails = true

[browser]
serverAddress = "localhost"

[browser.gatherUsageStats]
enabled = false
