[browser]
serverAddress = "localhost"
serverPort = 8501

[server]
headless = false
runOnSave = true

[client]
showErrorDetails = true

[runner]
magicEnabled = true

[browser.gatherUsageStats]
# 关闭匿名使用统计
enabled = false
